"""empty message

Revision ID: 292554285479
Revises: 325a1e8a6c94
Create Date: 2025-01-05 20:08:24.413352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292554285479'
down_revision = '325a1e8a6c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.execute("UPDATE invoices SET enable_downloads = False")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
